#!/bin/sh

### BEGIN INIT INFO
# Provides:          pwrmon 
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 45
# Default-Stop:      0 1 6
# Short-Description: Power Monitoring for PJ 
# Description: provide PJ power monitoring and reboon functionality
### END INIT INFO


PIDDIR=/var/run/pwrmon
PWRPID=$PIDDIR/pwrmon.pid
PWREXEC=/home/pi/utilities/pwrmon/pwrmon

# quiet shutdown with voltage drop of .3V
PWROPTS="-q 0.3"

# See if the daemons are there
test -x $PWREXEC || exit 0

. /lib/lsb/init-functions

case $1 in
	start)
		log_daemon_msg "Starting power monitoring" pwrmon 
		# Make sure we have our PIDDIR, even if it's on a tmpfs
		install -o root -g root -m 755 -d $PIDDIR

		if ! start-stop-daemon --start --background -m --oknodo --exec $PWREXEC --pidfile $PWRPID -- $PWROPTS > $PIDDIR/pwrmon.log; then
			log_end_msg 1
			exit 1
		fi

		log_end_msg 0
		;;
	stop)
		log_daemon_msg "Stopping power monitoring" smbd

		start-stop-daemon --stop --quiet --pidfile $PWRPID
		# Wait a little and remove stale PID file
		sleep 1
		if [ -f $PWRPID ] && ! ps h `cat $SMBDPID` > /dev/null
		then
			# Stale PID file, remove it
			rm -f $PWRPID
		fi

		log_end_msg 0

		;;
	reload|restart|force-reload)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: /etc/init.d/pwrmon {start|stop|reload|restart|force-reload}"
		exit 1
		;;
esac

exit 0
